name: Documentation Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install markdown-link-check
      run: npm install -g markdown-link-check

    - name: Check markdown links
      run: |
        find . -name "*.md" -not -path "./node_modules/*" | xargs markdown-link-check --config .github/markdown-link-check-config.json

    - name: Validate documentation structure
      run: |
        echo "Checking documentation structure..."
        echo "Products found: $(find products -name "*.md" -not -name "README.md" | wc -l)"
        echo "README files: $(find . -name "README.md" | wc -l)"

        # Check for required files
        required_files=("README.md" "LICENSE" "CONTRIBUTING.md")
        for file in "${required_files[@]}"; do
          if [[ ! -f "$file" ]]; then
            echo "❌ Missing required file: $file"
            exit 1
          else
            echo "✅ Found: $file"
          fi
        done
